/**
 * Prompt assembly, redaction and output schemas for the address / customer
 * dossiers generated by scripts/dossiers.ts (W1-D). Pure functions: no DB,
 * no network, so everything here is unit-tested in dossier-prompt.test.ts.
 */
import type Anthropic from "@anthropic-ai/sdk";
import { formatInTimeZone } from "date-fns-tz";
import { z } from "zod";
import { DOSSIER_MODEL } from "@/lib/anthropic";
import { BUSINESS_TZ } from "@/lib/time";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

export const DOSSIER_SYSTEM_PROMPT =
  "You write the front-desk memory card for an HVAC company. Only state what the notes and invoices support. " +
  "Prefer dates, technician first names, parts and outcomes. Never include door codes, phone numbers or emails. " +
  "If something is unresolved, say so.";

/** Hard cap per request (brief). The whole corpus is ~380K tokens, so this only bites on huge accounts. */
export const MAX_INPUT_TOKENS = 60_000;
/**
 * Calibrated on the first 40 batch results: billed input tokens were ~2x the
 * naive 3.5-chars/token guess. ~2.2 chars/token plus a fixed per-request
 * overhead (system prompt + JSON schema) tracks the API within ~10%.
 */
export const CHARS_PER_TOKEN = 2.2;
export const REQUEST_OVERHEAD_TOKENS = 500;
/** JSON output is ~300 tokens; the rest is headroom for adaptive thinking. */
export const MAX_OUTPUT_TOKENS = 3000;
export const DEFAULT_EFFORT: "low" | "medium" | "high" = "medium";
export const SUMMARY_MAX_WORDS = 90;
/** Asked-for length; the model drifts 5-15 words over whatever number it is given. */
export const SUMMARY_TARGET_WORDS = "45 to 75";

export const RISK_FLAGS = [
  "unpaid balance",
  "repeat callback",
  "unresolved issue",
  "aging equipment",
  "replacement recommended",
  "customer complaint",
  "canceled job",
  "warranty claim",
  "safety concern",
] as const;
export type RiskFlag = (typeof RISK_FLAGS)[number];

// ---------------------------------------------------------------------------
// Corpus shapes (built from the DB by the script)
// ---------------------------------------------------------------------------

export type CorpusNote = { seq: number; authorType: string; content: string };
export type CorpusItem = { name: string; type: string | null; amountCents: number };
export type CorpusJob = {
  id: string;
  invoiceNumber: string | null;
  description: string | null;
  workStatus: string;
  scheduledStart: Date | null;
  completedAt: Date | null;
  tags: string[];
  totalCents: number;
  outstandingCents: number;
  invoiceStatus?: string | null;
  /** Technician first names. */
  techs: string[];
  /** Address label; shown per job in customer corpora. */
  siteLabel?: string;
  notes: CorpusNote[];
  items: CorpusItem[];
};

export type AddressCorpus = {
  addressId: string;
  label: string;
  customer: { id: string; displayName: string; kind: string | null };
  jobs: CorpusJob[];
};

export type CustomerCorpus = {
  customerId: string;
  displayName: string;
  kind: string | null;
  company: string | null;
  sites: { addressId: string; label: string; jobCount: number }[];
  jobs: CorpusJob[];
  openBalanceCents: number;
};

// ---------------------------------------------------------------------------
// Redaction — the data already carries [code]/[phone]/[email] placeholders;
// this is the belt to those braces and must leave the placeholders intact.
// ---------------------------------------------------------------------------

const EMAIL_RE = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi;
const URL_RE = /\b(?:https?:\/\/|www\.)\S+/gi;
// North American 10-digit numbers with common separators; 4-digit invoice
// numbers and m/d dates do not match.
const PHONE_RE = /(?:\+?1[\s.-]?)?\(?\b\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}\b/g;
// "gate code 1234", "door code is 4321#", "lockbox: 0000", "code *5566"
const CODE_RE =
  /\b(lock ?box|(?:(?:gate|door|lock ?box|alarm|garage|entry|access|keypad|security|building|call ?box)\s+)?(?:code|pin|combo|combination|passcode))\b(\s*(?:is|are|:|#|=|-|of)?\s*)([#*]?\d[\d*#-]{2,9})/gi;

export function redact(text: string): string {
  return text
    .replace(EMAIL_RE, "[email]")
    .replace(URL_RE, "[link]")
    .replace(PHONE_RE, "[phone]")
    .replace(CODE_RE, "$1$2[code]");
}

// ---------------------------------------------------------------------------
// Access-note extraction (deterministic, stored redacted; the LLM only flags)
// ---------------------------------------------------------------------------

const ACCESS_RE =
  /\[code\]|gate code|door code|lock ?box|access (?:info|note|instruction|code)|garage code|alarm code|security (?:desk|guard|office|will)|call (?:ahead|before arriving|on arrival|upon arrival)|key (?:is )?(?:under|in the|at the|with|hidden)|front desk/i;

export function extractAccessNotes(notes: { content: string }[], maxChars = 400): string | null {
  const seen = new Set<string>();
  const hits: string[] = [];
  for (const n of notes) {
    for (const raw of n.content.split(/(?<=[.!?])\s+|\n+/)) {
      const s = collapse(redact(raw));
      if (!s || !ACCESS_RE.test(s)) continue;
      const key = s.toLowerCase();
      if (seen.has(key)) continue;
      seen.add(key);
      hits.push(s);
    }
  }
  if (!hits.length) return null;
  const joined = hits.join(" ");
  return joined.length > maxChars ? `${joined.slice(0, maxChars - 1)}…` : joined;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

export function estimateTokens(text: string): number {
  return REQUEST_OVERHEAD_TOKENS + Math.ceil(text.length / CHARS_PER_TOKEN);
}

export function wordCount(text: string): number {
  return text.trim().split(/\s+/).filter(Boolean).length;
}

function collapse(s: string): string {
  // Some imported notes carry literal backslash-n sequences.
  return s.replace(/\\n/g, " ").replace(/\s+/g, " ").trim();
}

function money(cents: number): string {
  return `$${(cents / 100).toFixed(2)}`;
}

function fmtDate(d: Date | null): string {
  return d ? formatInTimeZone(d, BUSINESS_TZ, "yyyy-MM-dd") : "unscheduled";
}

export function jobDate(j: Pick<CorpusJob, "completedAt" | "scheduledStart">): Date | null {
  return j.completedAt ?? j.scheduledStart;
}

/** Oldest first; jobs without any date go last. */
export function sortJobs<T extends Pick<CorpusJob, "completedAt" | "scheduledStart">>(jobs: T[]): T[] {
  return [...jobs].sort((a, b) => {
    const da = jobDate(a)?.getTime() ?? Number.POSITIVE_INFINITY;
    const db = jobDate(b)?.getTime() ?? Number.POSITIVE_INFINITY;
    return da - db;
  });
}

export function isCompleted(j: Pick<CorpusJob, "workStatus">): boolean {
  return j.workStatus.startsWith("complete");
}

/** Most recent completed visit, or null. */
export function lastVisitAt(jobs: CorpusJob[]): Date | null {
  let best: Date | null = null;
  for (const j of jobs) {
    if (!isCompleted(j)) continue;
    const d = jobDate(j);
    if (d && (!best || d > best)) best = d;
  }
  return best;
}

// ---------------------------------------------------------------------------
// Rendering with a token budget (oldest notes dropped first)
// ---------------------------------------------------------------------------

export type BuiltPrompt = {
  user: string;
  estTokens: number;
  notesTotal: number;
  notesOmitted: number;
};

function renderJob(j: CorpusJob, notes: CorpusNote[], omitted: number, withSite: boolean): string {
  const lines: string[] = [];
  const when = fmtDate(j.scheduledStart);
  const done = j.completedAt ? ` (completed ${fmtDate(j.completedAt)})` : "";
  lines.push(`### Job #${j.invoiceNumber ?? "n/a"} — ${when} — ${j.workStatus}${done}`);
  if (withSite && j.siteLabel) lines.push(`Site: ${j.siteLabel}`);
  lines.push(`Booked as: ${j.description?.trim() || "(no description)"}`);
  lines.push(`Techs: ${j.techs.length ? j.techs.join(", ") : "unassigned"}`);
  if (j.tags.length) lines.push(`Tags: ${j.tags.join(", ")}`);
  const status = j.invoiceStatus ? `, invoice ${j.invoiceStatus}` : "";
  lines.push(`Money: total ${money(j.totalCents)}, outstanding ${money(j.outstandingCents)}${status}`);
  if (j.items.length) {
    lines.push("Line items:");
    for (const it of j.items) lines.push(`- ${it.name}${it.type ? ` (${it.type})` : ""} ${money(it.amountCents)}`);
  }
  const header = omitted ? `Notes (${notes.length} shown, ${omitted} older omitted):` : `Notes (${notes.length}):`;
  lines.push(header);
  if (!notes.length && !omitted) lines.push("- (none)");
  for (const n of notes) lines.push(`- [${n.authorType}] ${collapse(redact(n.content))}`);
  return lines.join("\n");
}

function buildWithBudget(
  header: string,
  jobs: CorpusJob[],
  tail: string,
  withSite: boolean,
  maxTokens: number,
): BuiltPrompt {
  const sorted = sortJobs(jobs).map((j) => ({ ...j, notes: [...j.notes].sort((a, b) => a.seq - b.seq) }));
  // Global chronological note order = job order, then seq. `dropped` is a
  // prefix length over that order, so the oldest notes disappear first.
  const offsets: number[] = [];
  let total = 0;
  for (const j of sorted) {
    offsets.push(total);
    total += j.notes.length;
  }
  const render = (dropped: number) => {
    const parts = sorted.map((j, i) => {
      const drop = Math.max(0, Math.min(j.notes.length, dropped - offsets[i]));
      return renderJob(j, j.notes.slice(drop), drop, withSite);
    });
    return [header, ...parts, tail].join("\n\n");
  };
  let dropped = 0;
  let user = render(0);
  const step = Math.max(1, Math.ceil(total * 0.05));
  while (estimateTokens(user) > maxTokens && dropped < total) {
    dropped = Math.min(total, dropped + step);
    user = render(dropped);
  }
  return { user, estTokens: estimateTokens(user), notesTotal: total, notesOmitted: dropped };
}

const CONVENTIONS =
  `Money is in dollars. Dates are ${BUSINESS_TZ} calendar dates (yyyy-mm-dd). ` +
  "Notes are in the order they were written; [office] is the front desk, [tech] is the technician on site. " +
  "Placeholders like [code], [phone], [email] and [link] mark redacted data — never guess what they were.";

const SHARED_FIELD_RULES = [
  `- summary_md: ${SUMMARY_TARGET_WORDS} words (hard limit ${SUMMARY_MAX_WORDS}, count them) of plain spoken sentences (no headings, bullets or markdown symbols). ` +
    'Use month-day dates like "Apr 21" and technician first names. Say plainly when something is unresolved.',
  "- last_visit_summary: one sentence on the most recent completed visit (date, tech, what was done). If nothing was completed yet, say what is scheduled.",
  "- open_issues: items still unresolved as of the latest note — parts on order, estimates awaiting approval, callbacks owed, promised follow-ups. Empty if none.",
  "- risk_flags: choose only from the allowed values and only when the record clearly supports each one.",
];

// ---------------------------------------------------------------------------
// Address prompt
// ---------------------------------------------------------------------------

export type BuildOpts = { today: string; maxTokens?: number };

export function buildAddressPrompt(c: AddressCorpus, opts: BuildOpts): BuiltPrompt {
  const header = [
    "# Service address — source record",
    `Today: ${opts.today}`,
    `Address: ${c.label}`,
    `Customer: ${c.customer.displayName} (${c.customer.kind ?? "unknown kind"})`,
    `Jobs at this address: ${c.jobs.length} (oldest first).`,
    CONVENTIONS,
  ].join("\n");
  const tail = [
    "# Output",
    "Return the memory card as JSON matching the schema. Field rules:",
    SHARED_FIELD_RULES[0],
    SHARED_FIELD_RULES[1],
    "- equipment: short strings for each system or major part named in the notes or line items (kind, brand, model, tonnage, install date or age when stated). Empty if none.",
    SHARED_FIELD_RULES[2],
    "- recurring_issues: problems that came up on two or more visits. Empty if none.",
    "- access_notes_present: true only if the notes contain access instructions (door, gate or lockbox codes, security desk, call-ahead rules). Never repeat those instructions anywhere in the output.",
    "- warranty_notes: one sentence on warranty facts stated in tags, notes or line items (labor warranty, registration status, WARRANTY parts, claims). Empty string if none.",
    SHARED_FIELD_RULES[3],
  ].join("\n");
  return buildWithBudget(header, c.jobs, tail, false, opts.maxTokens ?? MAX_INPUT_TOKENS);
}

// ---------------------------------------------------------------------------
// Customer prompt
// ---------------------------------------------------------------------------

const MAX_SITE_LINES = 40;

export function buildCustomerPrompt(c: CustomerCorpus, opts: BuildOpts): BuiltPrompt {
  const siteLines = c.sites
    .slice(0, MAX_SITE_LINES)
    .map((s) => `- ${s.label} — ${s.jobCount} job${s.jobCount === 1 ? "" : "s"}`);
  if (c.sites.length > MAX_SITE_LINES) siteLines.push(`- …and ${c.sites.length - MAX_SITE_LINES} more sites`);
  const header = [
    "# Customer — source record",
    `Today: ${opts.today}`,
    `Customer: ${c.displayName} (${c.kind ?? "unknown kind"})${c.company ? `, company: ${c.company}` : ""}`,
    `Open balance across all jobs: ${money(c.openBalanceCents)}`,
    `Service sites (${c.sites.length}):`,
    ...siteLines,
    `Jobs (${c.jobs.length}, oldest first; each job names its site).`,
    CONVENTIONS,
  ].join("\n");
  const tail = [
    "# Output",
    "Return the customer memory card as JSON matching the schema. Field rules:",
    `- summary_md: ${SUMMARY_TARGET_WORDS} words (hard limit ${SUMMARY_MAX_WORDS}, count them) of plain spoken sentences (no headings, bullets or markdown symbols): who they are (homeowner, property manager or business, how many sites), ` +
      "how long they have used us, what work is typical, the most recent activity, anything open, and payment posture if the record shows it.",
    SHARED_FIELD_RULES[1],
    "- preferences.preferred_techs: technician first names the customer asked for or that the office deliberately keeps sending. Empty if the notes do not say.",
    "- preferences.scheduling: how they like visits booked (times of day, notice, who approves work). Empty if unknown.",
    "- preferences.contact: who the on-site contact is (owner, tenant, property manager, front desk) and how the office reaches them — never numbers or emails.",
    "- preferences.billing: how they pay, PO or approval requirements, disputes or slow payment. Empty if unknown.",
    SHARED_FIELD_RULES[2],
    SHARED_FIELD_RULES[3],
  ].join("\n");
  return buildWithBudget(header, c.jobs, tail, true, opts.maxTokens ?? MAX_INPUT_TOKENS);
}

// ---------------------------------------------------------------------------
// Output schemas (JSON schema for the API, zod for validation on ingest)
// ---------------------------------------------------------------------------

const stringArray = (description: string) => ({ type: "array", description, items: { type: "string" } });

export const ADDRESS_OUTPUT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: [
    "summary_md",
    "last_visit_summary",
    "equipment",
    "open_issues",
    "recurring_issues",
    "access_notes_present",
    "warranty_notes",
    "risk_flags",
  ],
  properties: {
    summary_md: { type: "string", description: `Spoken-friendly summary, at most ${SUMMARY_MAX_WORDS} words.` },
    last_visit_summary: { type: "string", description: "One sentence on the most recent completed visit." },
    equipment: stringArray("Systems and major parts named in the record."),
    open_issues: stringArray("Unresolved items as of the latest note."),
    recurring_issues: stringArray("Problems seen on two or more visits."),
    access_notes_present: { type: "boolean", description: "True if the notes contain access instructions." },
    warranty_notes: { type: "string", description: "One sentence of warranty facts, or empty string." },
    risk_flags: { type: "array", items: { type: "string", enum: [...RISK_FLAGS] } },
  },
} as const;

export const CUSTOMER_OUTPUT_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["summary_md", "last_visit_summary", "preferences", "open_issues", "risk_flags"],
  properties: {
    summary_md: { type: "string", description: `Spoken-friendly summary, at most ${SUMMARY_MAX_WORDS} words.` },
    last_visit_summary: { type: "string", description: "One sentence on the most recent completed visit." },
    preferences: {
      type: "object",
      additionalProperties: false,
      required: ["preferred_techs", "scheduling", "contact", "billing"],
      properties: {
        preferred_techs: stringArray("Technician first names the customer prefers."),
        scheduling: stringArray("Scheduling preferences."),
        contact: stringArray("Who the on-site contact is and how the office reaches them, without numbers or emails."),
        billing: stringArray("Payment and approval notes."),
      },
    },
    open_issues: stringArray("Unresolved items as of the latest note."),
    risk_flags: { type: "array", items: { type: "string", enum: [...RISK_FLAGS] } },
  },
} as const;

export const addressDossierOutput = z.strictObject({
  summary_md: z.string().min(1),
  last_visit_summary: z.string(),
  equipment: z.array(z.string()),
  open_issues: z.array(z.string()),
  recurring_issues: z.array(z.string()),
  access_notes_present: z.boolean(),
  warranty_notes: z.string(),
  risk_flags: z.array(z.enum(RISK_FLAGS)),
});
export type AddressDossierOutput = z.infer<typeof addressDossierOutput>;

export const customerDossierOutput = z.strictObject({
  summary_md: z.string().min(1),
  last_visit_summary: z.string(),
  preferences: z.strictObject({
    preferred_techs: z.array(z.string()),
    scheduling: z.array(z.string()),
    contact: z.array(z.string()),
    billing: z.array(z.string()),
  }),
  open_issues: z.array(z.string()),
  risk_flags: z.array(z.enum(RISK_FLAGS)),
});
export type CustomerDossierOutput = z.infer<typeof customerDossierOutput>;

// ---------------------------------------------------------------------------
// Batch requests
// ---------------------------------------------------------------------------

export type DossierKind = "address" | "customer";

export function customIdFor(kind: DossierKind, id: string): string {
  return `${kind === "address" ? "addr" : "cust"}-${id}`;
}

export function parseCustomId(customId: string): { kind: DossierKind; id: string } | null {
  // Batch custom_ids must match ^[a-zA-Z0-9_-]{1,64}$ (no colons).
  const m = /^(addr|cust)-(.+)$/.exec(customId);
  if (!m) return null;
  return { kind: m[1] === "addr" ? "address" : "customer", id: m[2] };
}

export type RequestOpts = BuildOpts & { effort?: "low" | "medium" | "high" };

type BatchRequest = Anthropic.Messages.BatchCreateParams.Request;

function toRequest(customId: string, user: string, schema: object, opts: RequestOpts): BatchRequest {
  return {
    custom_id: customId,
    params: {
      model: DOSSIER_MODEL,
      max_tokens: MAX_OUTPUT_TOKENS,
      system: DOSSIER_SYSTEM_PROMPT,
      thinking: { type: "adaptive" },
      output_config: {
        effort: opts.effort ?? DEFAULT_EFFORT,
        format: { type: "json_schema", schema: schema as Record<string, unknown> },
      },
      messages: [{ role: "user", content: user }],
    },
  };
}

export function buildAddressRequest(c: AddressCorpus, opts: RequestOpts): { request: BatchRequest; built: BuiltPrompt } {
  const built = buildAddressPrompt(c, opts);
  return { request: toRequest(customIdFor("address", c.addressId), built.user, ADDRESS_OUTPUT_SCHEMA, opts), built };
}

export function buildCustomerRequest(c: CustomerCorpus, opts: RequestOpts): { request: BatchRequest; built: BuiltPrompt } {
  const built = buildCustomerPrompt(c, opts);
  return { request: toRequest(customIdFor("customer", c.customerId), built.user, CUSTOMER_OUTPUT_SCHEMA, opts), built };
}
