import "dotenv/config";
import { randomBytes } from "node:crypto";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { and, eq, inArray, sql as dsql } from "drizzle-orm";
import { db, sql as pg } from "./index";
import { employees, users } from "./schema";
import { hashPassword, normalizeEmail } from "../lib/auth";
import { newId } from "../lib/ids";

/**
 * pnpm db:seed-users
 *
 * Creates office logins (PLAN §3 D5): every active employee whose role is
 * admin or office, plus `owner@` and `grader@`. Idempotent: upserts by email,
 * never overwrites an existing password hash, and keeps previously generated
 * passwords by reading docs/CREDENTIALS.local.md (gitignored) before writing it.
 *
 * If the employees table has not been imported yet, the script seeds owner and
 * grader, then polls for staff rows for up to SEED_USERS_WAIT_MINUTES (default
 * 10; pass --no-wait to skip) instead of seeding placeholders.
 */

const DOMAIN = "gulfbreezeair.demo";
const CREDENTIALS_PATH = path.resolve(process.cwd(), "docs/CREDENTIALS.local.md");
const STAFF_ROLES = ["admin", "office"];

type Role = "owner" | "admin" | "office" | "tech";
type SeedUser = { email: string; name: string; role: Role; employeeId: string | null };

function generatePassword(): string {
  // 12 chars from an unambiguous alphabet (no 0/O/1/l/I).
  const alphabet = "abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789";
  const bytes = randomBytes(12);
  return Array.from(bytes, (b) => alphabet[b % alphabet.length]).join("");
}

function slug(s: string): string {
  return s
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "");
}

function readExistingPasswords(): Map<string, string> {
  const out = new Map<string, string>();
  if (!existsSync(CREDENTIALS_PATH)) return out;
  for (const line of readFileSync(CREDENTIALS_PATH, "utf8").split("\n")) {
    const m = line.match(/^\|\s*[^|]*\|\s*([^|\s]+@[^|\s]+)\s*\|\s*[^|]*\|\s*`([^`]+)`\s*\|/);
    if (m) out.set(normalizeEmail(m[1]), m[2]);
  }
  return out;
}

function writeCredentials(rows: Array<SeedUser & { password: string }>) {
  const lines = [
    "# Local credentials (do not commit)",
    "",
    `Generated by \`pnpm db:seed-users\` on ${new Date().toISOString()}. Re-running keeps existing passwords.`,
    "",
    "| Name | Email | Role | Password |",
    "|---|---|---|---|",
    ...rows.map((r) => `| ${r.name} | ${r.email} | ${r.role} | \`${r.password}\` |`),
    "",
  ];
  writeFileSync(CREDENTIALS_PATH, lines.join("\n"), { mode: 0o600 });
}

async function staffFromEmployees(): Promise<SeedUser[]> {
  const rows = await db
    .select({ id: employees.id, firstName: employees.firstName, lastName: employees.lastName, role: employees.role })
    .from(employees)
    .where(and(inArray(dsql`lower(${employees.role})`, STAFF_ROLES), eq(employees.active, true)))
    .orderBy(employees.role, employees.firstName);
  return rows.map((e) => ({
    email: `${slug(e.firstName)}.${slug(e.lastName)}@${DOMAIN}`,
    name: `${e.firstName} ${e.lastName}`.trim(),
    role: e.role.toLowerCase() === "admin" ? "admin" : "office",
    employeeId: e.id,
  }));
}

async function upsert(seed: SeedUser[], passwords: Map<string, string>) {
  for (const u of seed) {
    let password = passwords.get(u.email);
    if (!password) {
      password = generatePassword();
      passwords.set(u.email, password);
    }
    const passwordHash = await hashPassword(password);
    await db
      .insert(users)
      .values({ id: newId("usr"), email: u.email, name: u.name, role: u.role, passwordHash, employeeId: u.employeeId })
      .onConflictDoUpdate({
        target: users.email,
        // Never rotate an existing password; do refresh display fields.
        set: { name: u.name, role: u.role, employeeId: u.employeeId },
      });
  }
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function main() {
  const noWait = process.argv.includes("--no-wait");
  const waitMinutes = Number(process.env.SEED_USERS_WAIT_MINUTES ?? 10);
  const passwords = readExistingPasswords();

  const fixed: SeedUser[] = [
    { email: `owner@${DOMAIN}`, name: "Owner", role: "owner", employeeId: null },
    { email: `grader@${DOMAIN}`, name: "Grader", role: "admin", employeeId: null },
  ];
  await upsert(fixed, passwords);
  // Write owner/grader now so the file is useful even while we wait for the import.
  writeCredentials(fixed.map((u) => ({ ...u, password: passwords.get(u.email)! })));

  let staff = await staffFromEmployees();
  const deadline = Date.now() + waitMinutes * 60_000;
  while (staff.length === 0 && !noWait && Date.now() < deadline) {
    console.log("employees table has no admin/office rows yet (import in progress?); retrying in 30s");
    await sleep(30_000);
    staff = await staffFromEmployees();
  }
  if (staff.length === 0) {
    console.warn("no admin/office employees found; only owner and grader were seeded. Re-run after `pnpm import`.");
  }
  await upsert(staff, passwords);

  const all = [...fixed, ...staff];
  writeCredentials(all.map((u) => ({ ...u, password: passwords.get(u.email)! })));
  console.log(`seeded ${all.length} users (${staff.length} from employees). Credentials: ${CREDENTIALS_PATH}`);
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(() => pg.end({ timeout: 5 }));
